### ISSUE TITLE
CDFTOOLS port on GitHub

### ISSUE THREAD

**Issue by molines** [meom-group/CDFTOOLS#1]
## TODO list
- [x] Add README.md file : need to be improved
- [X] Licence CeCILL : add a link to web page
- [ ] Need to upgrade obsolete DOC directory with rst files.
